--- #YAML:1.0
name:                Module-Starter-Plugin-TT2
version:             0.123
abstract:            TT2 templates for Module::Starter::Template
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Module::Starter:               1.2501
    Template:                      2
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
