# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Starter-Plugin-TT2
version:      0.121
version_from: lib/Module/Starter/Plugin/TT2.pm
installdirs:  site
requires:
    Module::Starter:               1.2501
    Template:                      2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
